[tool.poetry]
name = "youtube-shorts-automation"
version = "0.1.0"
description = "A python project to make and upload Youtube shorts video"
authors = ["rajathjn <rajathjnx@gmail.com>"]
license = "GNU GENERAL PUBLIC LICENSE"
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "~3.12"
requests = "^2.32.3"
beautifulsoup4 = "^4.12.3"
discord-webhook = "^1.3.1"
praw = "^7.8.1"
unidecode = "^1.3.8"
ftfy = "^6.3.1"
language-tool-python = "^2.8.2"
setuptools = "^75.8.0"
scikit-image = "^0.25.1"
pydub = "^0.25.1"
whisperx = "^3.3.1"
rapidfuzz = "^3.11.0"
transformers = "^4.48.1"
diffusers = "^0.32.2"
accelerate = "^1.3.0"
wheel = "^0.45.1"
xformers = {version = "^0.0.29.post1", source = "pytorch-cu124"}
torch = {version = "^2.5.1", source = "pytorch-cu124"}
torchvision = {version = "^0.20", source = "pytorch-cu124"}
torchaudio = {version = "^2.5.1", source = "pytorch-cu124"}
ctranslate2 = "^4.4"

[[tool.poetry.source]]
name = "pytorch-cu124"
url = "https://download.pytorch.org/whl/cu124"
priority = "explicit"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.4"
pre-commit = "^4.0.1"
pytest-cov = "^6.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
testpaths = [
    "tests",
]
