[project]
name = "ShortsMaker"
version = "0.2"
description = "A python project to make and upload Youtube shorts video"
authors = [
    {name = "rajathjn",email = "rajathjnx@gmail.com"}
]
license = "GPL-3.0-or-later"
readme = "README.md"
requires-python = ">=3.12,<3.13"
classifiers = [
  "Development Status :: 3 - Alpha",
  "Intended Audience :: Developers",
  "Programming Language :: Python :: 3.12",
]
dependencies = [
    "wheel (>=0.45.1,<0.46.0)",
    "setuptools (>=75.8.0,<76.0.0)",
    "requests (>=2.32.3,<3.0.0)",
    "beautifulsoup4 (>=4.12.3,<5.0.0)",
    "discord-webhook (>=1.3.1,<2.0.0)",
    "praw (>=7.8.1,<8.0.0)",
    "unidecode (>=1.3.8,<2.0.0)",
    "ftfy (>=6.3.1,<7.0.0)",
    "language-tool-python (>=2.8.2,<3.0.0)",
    "scikit-image (>=0.25.1,<0.26.0)",
    "pydub (>=0.25.1,<0.26.0)",
    "whisperx (>=3.3.1,<4.0.0)",
    "rapidfuzz (>=3.11.0,<4.0.0)",
    "transformers (>=4.48.1,<5.0.0)",
    "diffusers (>=0.32.2,<0.33.0)",
    "accelerate (>=1.3.0,<2.0.0)", #
    "ctranslate2 (<4.5)", #
    "xformers (>=0.0.29.post1,<0.0.30)", #
    "torch (<2.6)",
    "torchaudio (<2.6)",
    "torchvision (<0.21)",
    "langchain-community (>=0.3.16,<0.4.0)", #
    "outlines (>=0.1.14,<0.2.0)", #
    "datasets (>=3.2.0,<4.0.0)", #
    "ollama (>=0.4.7,<0.5.0)",
    "langchain-ollama (>=0.2.3,<0.3.0)",
    "hatchling>=1.27.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[[tool.uv.index]]
name = "pytorch-cu124"
url = "https://download.pytorch.org/whl/cu124"
explicit = true

[tool.uv.sources]
xformers = {index = "pytorch-cu124"}
torch = {index = "pytorch-cu124"}
torchaudio = {index = "pytorch-cu124"}
torchvision = {index = "pytorch-cu124"}

[tool.pytest.ini_options]
testpaths = [
    "tests",
]

[dependency-groups]
dev = [
    "pre-commit>=4.1.0",
    "pytest>=8.3.4",
    "pytest-cov>=6.0.0",
    "ruff>=0.9.4",
]

[tool.ruff]
# Set the maximum line length to 79.
exclude = [
    ".pytest_cache",
    ".venv",
    ".vscode",
    ".idea"
]
line-length = 200

[tool.ruff.lint]
extend-select = [
    "UP",  # pyupgrade
    "D",   # pydocstyle
    "I",   # isort
]

[tool.ruff.lint.pydocstyle]
convention = "google"
