name: ShortsMaker

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DISCORD_WEBHOOK_URL: "https://discord.com/api/webhooks/xxx"
    steps:
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: Setup FFmpeg
        uses: federicocarboni/setup-ffmpeg@v3.1
      - name: Checkout the repository
        uses: actions/checkout@main
      - name: Install the latest version of uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          pyproject-file: "pyproject.toml"
      - name: Install dependencies
        run: uv sync --frozen --extra cpu
      - name: Run tests
        run: uv run --frozen pytest
